# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cfg' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for cfg
	pod 'FlyoverKit', '~> 1.2.0'
	pod 'GoogleSignIn'
	pod 'Firebase/Auth'
	pod 'Firebase/Analytics'
	pod 'Firebase/Storage'
	pod 'FirebaseCore'
	pod 'FirebaseFirestore'
	
  target 'cfgTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'cfgUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
